### PR TITLE
2020

### PR DESCRIPTION
**Pull request by mySocietyClive**
# TO-DO

(Feel free to add new items. Remove items once you’ve done them, even if you haven’t pushed yet.)

## Thank you

---

Hi @zarino, @wrightmartin,

I've done a migration of content (text from Myf's doc), all images are incorrect as they are just the images from 2019.

I've made it as far as the Thank you section (the 'To our volunteers' section and below isn't done yet and still needs 2020 text).

I've attempted to reuse components/elements that might work in some instances, but it would be good to get your guys input on what works best:)

Thanks
Clive

### CODE REVIEW

**Comment by MyfanwyNixon** [comment]
Thanks! I'll work through these comments. 

>I (@zarino) feel like we need to standardise on our titles for subsections of the report. So, "facts and figures" is always stats about our websites’ usage over the year. "What did you do with our stuff" is always examples of things that other people have done / written using our sites/data/services. @MyfanwyNixon thoughts?

Yes - that's definitely the intention. I just started giving it a proof and noticed exactly this, that the Transparency section's Facts and Figures weren't facts and figures at all. For some reason the actual figures have ended up in 'what did you do with our stuff'. So a better arrangement of this content would be to move the 'In the UK…' and 'And around the world...' sections up so that they are under 'The facts and figures'.
'Better understanding' can go under 'Keeping an eye on our rights' and 'Who’s the boss?' is a 'Who we worked with' item.
Sorry - I'm not sure how these became so muddled. I'll work through the rest of the report when I've answered these queries and see if there are any other similar issues.

> Some of the life in lockdown quotes are a bit long. I wonder how @MyfanwyNixon feels about editing them down to be a bit snappier?

No problem - I'll do that once I've worked through these comments.

>Would be nice to get some photos in the life in lockdown sections.

Don't forget we asked people to provide us with photos. They're here: https://drive.google.com/drive/folders/1CvBz2zb8IdlQEWZtVMh2ZMFWTD9MxgTy?usp=sharing

**Comment by MyfanwyNixon** [comment]
### Transparency

> "What we did in 2020" There are five items here. Wonder whether we can make it four? Or six? @MyfanwyNixon
These are now 4 so I guess not a problem now.

### Democracy

> "What did you do with our stuff?" @MyfanwyNixon could you supply link text for the 4 publications (i-D magazine; Stylist; Dazed; Glamour)?

[i-D magazine](https://i-d.vice.com/en_uk/article/4aywy3/write-to-your-uk-mp-demand-action-solidarity-anti-racism-protestors) said "Start by holding your political representatives to account".
[Stylist](https://www.stylist.co.uk/life/how-to-write-to-mp-about-racism-black-lives-matter/395966/) urged readers, "Write to your MP to demand government action on racism".
[Dazed](https://www.dazeddigital.com/politics/article/49444/1/how-to-support-black-lives-matter-can-not-attend-the-protests-george-floyd) pointed out the ways to support Black Lives Matter even if you couldn't join a protest.
And [Glamour](https://www.glamourmagazine.co.uk/article/how-to-write-to-your-mp-uk) suggested, 'Use your outrage to affect long-term change".

### SocietyWorks

>"Who we worked with…" @MyfanwyNixon for layout to work could we remove one to make it 6 items? Or if you have one or two more that makes it up to 9 that would better

Drop Highways England, as we don't have anything to link to.

### Community

>@MyfanwyNixon could you supply headline for"/PLACEHOLDER HEADLINE/" (after "What we did in 2020")

This is a 'What's been most rewarding about Community this year?' section. Same for the placeholder title in TICTeC - can be 'What's been most fun about TICTeC this year?'. But in that case I think 'It’s been a super challenging year for event organisers everywhere!' is more of a 'life in lockdown' quote.

### Thank you

>Duplicated content between the "what are you looking forward to in 2021?" chat bubbles at the end of the Thank you section, and the chat bubbles in the "life in lockdown" section immediately before.

Looks like this has been sorted?

I think Mark suggested cutting the  'More of the same – at mySociety that’s a good thing.' quote as well.

**Comment by MyfanwyNixon** [comment]
Here are some suggested 'Life in lockdown' edits:

Original
>Nothing was more challenging than having the kids home for four months while trying to balance our jobs and other commitments. Luckily mySociety is the best possible place to work at times like this. I was given real flexibility and empowered to make the situation work for myself and my family.

Edit to: 
Having the kids home while trying to balance our jobs and other commitments. Luckily mySociety gave me real flexibility, empowering us to make the situation work for the family.

Original
>I worked with a toddler in tow — who doesn’t love having their laptop lid closed mid conference call?

Edit to keep 'mid' and 'conference' on the same line, separated by a hyphen:
I worked with a toddler in tow — who doesn’t love having their laptop lid closed mid-conference call?

Original
>Migrating all of our digital transformation work with international parliaments to remote-only activity has been really difficult. It is so much harder to build rapport with people, get a sense of how people use technology, and how the digital and physical space in parliaments overlaps, when you are only able to speak to people via Skype. It is made even more difficult when you need simultaneous translation to communicate.

Edit to:

Complex digital transformation work with international parliaments is really difficult when you can only speak via Skype. And all the more difficult when you need simultaneous translation to communicate!

Original
>I pretty much work entirely from home now, rather than going out on the road for meetings as I’m used to – my last in-person meeting was on 11 March!

Edit to:
No more going out on the road for meetings like I used to – my last in-person meeting was on 11 March!

Original
>My usual role of organising and managing in-person conferences and events has massively changed this year due to COVID. I do really miss seeing people and the buzz I get from organising in-person convenings 😞

Edit to:
My role of organising in-person events has massively changed this year. I do really miss seeing people and the buzz I get from organising in-person convenings 😞

Original
>Yeah. I was sceptical that we would get the same kind of participation and collaboration as we do in person. But actually, I’ve found we get more – maybe the introverts are able to contribute more this way.

Edit to:
I was sceptical that we would get the same kind of participation as we do in person. But actually, I’ve found we get more – maybe the introverts are able to contribute more this way.

Original
>Moved into my youngest child’s old bedroom/nursery – great having my own office. The monkeys on the wall are an added benefit 🐒

Edit to:
Moved into my youngest child’s old bedroom – great having my own office. The monkeys on the wall are an added benefit 🐒

Original
>It has made me appreciate how flexible, principled, and supportive mySociety is as an organisation to work for. It really feels like we’re all here for each other, and it’s been a joy seeing these people every day, even through the toughest of times.

Edit to: 
>It has made me appreciate how flexible, principled, and supportive mySociety is as an organisation to work for. It really feels like we’re all here for each other, even through the toughest of times.

Original
>What did our team get up to, way from their computers?

Noticed a typo. Edit to:
What did we all get up to, *away* from our computers?

Also please add these two, before the final 'I got engaged!':

- I helped design and deliver two curriculums for a coding bootcamp, funded by the West Midlands Authority.

- My team won a hackathon at Newspeak House focused on helping MPs, and supported them with their Coronavirus Tech Handbook initiative.

**Comment by MyfanwyNixon** [comment]
Here are some extra proofing/style comments:

### General

- Should we include some form of index/anchor links so people can skip straight to the parts that interest them the most? It feels like quite a lot to ask people to read the entire thing, and I bet drop-out rates will be quite high.

**Mark's intro**

- "so we can get in first with the _comment_"  > change to "commentary"

- "We rediscovered that thing called Society whilst renaming our businesses"; > change to "We renamed our businesses, re-emphasising the importance of that little thing called 'society' along the way"

- Reading through this and into the next section I notice there are an awful lot of uses of the word 'so: 

1. And so, our major theme for 2020? 
2. So what’s new?
3. And so, that meant saying goodbye to
4. So long and thanks for all the UKCOD

Let's edit to:
1. Our major theme for 2020? 
3. Sadly, that meant saying goodbye to

### Life in lockdown (1)

- This year has been one unlike any other. - drop 'one'

- We asked the team what their thoughts are about life in lockdown, and we’ve included a few of their comments throughout this annual report."

Change to: "We asked the team for their thoughts on life during lockdown."

- > including bringing Pro functionality to the Czech Republic, Belgium, France, Sweden and European Union site AskTheEU.

Might be nice to link to the various sites. 
Czech: https://www.infoprovsechny.cz/
Belgium: https://transparencia.be/
France: https://madada.fr/
Sweden: https://handlingar.se/
AskTheEU: https://www.asktheeu.org/

- Keeping an eye on our rights
This is a good solution to the fifth item on the list and it is definitely important enough to take up the whole width of the page. I wonder if it might be nice for it also to have some sort of image so it isn't skimmed over?

- Facts and figures - see my earlier comment about switching some content around.

OK - going to have some lunch now, but I'll return to this afterwards.

**Comment by MyfanwyNixon** [comment]
### Transparency

- Looks like these have been edited down but that this has introduced some style issues/typos:

>Privacy International ran a vital FOI-based investigation surveillance tech used by police

**Change to** 'investigation on surveillance tech'.

> FOI helps halt unwanted housing development in Haringey

**Change to** FOI helped halt an unwanted housing development in Haringey.

> The Higher Education Policy Institute, uncovered the strains that staff are under

**Change to** The Higher Education Policy Institute uncovered the strains that staff are under
[Drop comma]

- Tweet:

>Can’t imagine how long it would take to send batch FOI’s without @WhatDoTheyKnow, literally a journalist’s dream.

As we've faked this up it is tempting to drop the apostrophe, which is grammatically incorrect.

- Staff quotes:

>It was great to work with the Government Digital Service this year on the Global Digital Marketplace Programme. While on the surface, a digital project on procurement systems might seem a little dull, it was really an interesting project working with governments in South Africa, Indonesia, Malaysia and Mexico on how they could improve the transparency of the public procurement process to reduce waste, inefficiency and tackle corruption.

Edit down to:

It was great to work with the Government Digital Service. A project on procurement systems might sound dull,  but it was really interesting working with governments in four countries to improve the transparency of the process and reduce waste, inefficiency and tackle corruption.

>A nice small-scale interaction was chatting to Cardiff Civic Society, and then later seeing them making regular use of WhatDoTheyKnow in their mission to help preserve public spaces in Cardiff.

Small style edit to:
A nice small-scale interaction was chatting to Cardiff Civic Society, and then later seeing them making regular use of WhatDoTheyKnow in their mission to help preserve public spaces in the city.

### Democracy

- >How did they vote. And with the official House of Commons feed no longer allowed to tweet the results of votes, our email alerts become all the more important.

**Edits:** Add a question mark instead of full stop after "How did they vote" (or change to 'How they voted').
Drop the 'And' - I think this only works if you're reading one below the other in the text document.

- >As a designer, it was fascinating seeing how another country’s parliament works, and the challenges faced by MPs and their support staff, in representing a citizenry with completely different economic and technological challenges to anywhere else I’d seen.

**Edit to:**
As a designer, it was fascinating to see how another country’s parliament works — and the challenges faced by MPs and their staff, in representing a citizenry with completely different economic and technological challenges.

- >Work we did with the Moroccan parliament demonstrated that citizens there preferred some of the changes to parliamentary activity made as a result of COVID-19, especially the move to broadcast parliamentary sessions on TV.

**Edit to:**
Work we did with the Moroccan parliament demonstrated that citizens there preferred some of the changes made as a result of COVID-19, especially the move to broadcast sessions on TV.

- >and they also flooded to share their feelings with their MPs: we had 23 times the usual visitors to the site.

**Edit to:**
and they also flooded onto WriteToThem to share their feelings with their MPs: we had 23 times the usual visitors to the site.

>What’s the youth.
Oh, I was aiming for a pun on 'what's the use' but it doesn't really work does it?! Maybe change to: 

**Youth club.** mySociety’s Research team worked with the Inter-Parliamentary Union on their biannual report on Youth Representation in National Parliaments — the main global resource on the topic.

- >After eight productive years, we said au revoir to Mzalendo, as the Kenyan team were happy to run things all on their own.

Change 'were' to 'are now'.

**Comment by MyfanwyNixon** [comment]
### Community

- Placeholder headline: This is one of the "What's been most rewarding about working on Community this year?" titles.

- >The smaller projects we’ve worked on this year show us arming citizens with the knowledge and tools they need to demand better, or get their voice heard, for real, fundamental social change.

**Edit to:** 
The smaller projects we’ve worked on this year give citizens the knowledge and tools they need to demand real social change.

- "with shared data standards"
I think this needs a ... before it to show the connection with the title.

### SocietyWorks

->This year we’ve been getting well into the world of waste and bins — improving the online services around them for everyone.

**Edit to:**
This year we’ve been getting well into the world of waste and bins — improving the online services around rubbish collection for everyone.

- > New ways to locate yourselfon the FixMyStreet map.

Typo - needs space between 'yourself' and 'on'.

->New progressive web app functionality means FixMyStreet can act just like an app on your phone or device.

**Edit to:**
[New PWA technology](https://www.societyworks.org/2020/12/10/progressive-web-apps-what-are-they-and-what-can-they-do-for-us/) means FixMyStreet can act just like an app on your phone or device.

(link added, too)

->Precisely pinpoint that tree thanks to EzyTreev integration.

**Edit to:**
Pinpoint that tree precisely, thanks to EzyTreev integration.

-a new service for Transport Focus: Sort My Sign.

This seems really short in situ, so let's edit to:

A new service helps people report dirty, broken, or missing road signs to  Transport Focus — [but don't report and drive](https://www.societyworks.org/2020/03/06/sort-my-sign-mapping-road-signs-for-transport-focus/)!

- Say Cheese
We abandoned this section (as per the Google Doc) and instead, right below the client logos, it's now
>**Roll call** New authorities to integrate with FixMyStreet Pro this year are **Hackney**, **Highways England**, **Transport Focus**, **Cheshire East** and — just this minute — **Central Bedfordshire**, bringing the total number of Pro bodies to 22. 

- 'Who we worked with' section has been repeated - one at the top as full width items and then again in the smaller grid.

**Comment by MyfanwyNixon** [comment]
### Climate

->we’re working on some of the tools you need to fight climate breakdown.

**Change to:**
"we’re working on some of the tools you need to act on the climate emergency."

->Together, they create new policies and assess the improvements we can make.

**Change to:**
This group assesses ideas for improvement and recommends new policies for the organisation to take on.

-  a huge contribution of active citizenship
needs a full stop

-Friends of the Earth created this toolwith our MapIt API
needs a space between 'tool' and 'with'.

->The most rewarding thing I’ve done this year was to be involved in the Climate Assembly. This was an important project both in terms of its potential impact on Climate related policy and as a positive example of participatory democracy that demonstrated a more deliberative and consensual rather than divisive and confrontational form of debate and decision making.

**Edit to:**
The Climate Assembly was important, both in terms of its potential impact on Climate related policy and as a positive example of participatory democracy. It showed that decision making could be deliberative and consensual rather than divisive and confrontational.

**Comment by MyfanwyNixon** [comment]
### TICTeC

->And so, it was a quick turnaround time: 

Change to: "And so, it was time for a quick turnaround:"

- Numbers:
Are these correct or are they just copied from last year? Gemma can provide stats if we need to update them, no doubt.

-> Nanjala Nyabola’s keynote session felt more intimate,

Drop 'more'.

- Diginomica quote - not sure it works cut like this? Could put the 'Diginomic said they' inside the speech bubble; I think it'd still work.

- Placeholder title: can we just drop it and not have a title at all?

- "Want some nice tweets perhaps? If so:"
Ha ha drop this, that was Gemma's comment to me :D

- On mitigating the climate crisis - can link this to https://www.mysociety.org/2020/12/04/what-role-for-civic-tech-and-open-data-in-mitigating-the-climate-crisis/

- Second placeholder title: this is a 'What was most fun about TICTeC this year?' staff section.

**Comment by MyfanwyNixon** [comment]
### Thank you section

- Funding opportunities
This looks a little dry and unlikely to attract big philanthropists to click through. Anything we can do to quickly jazz it up? Even if only a few stars and sparkles? :)

- Volunteers 

I think these should be:
Richard Taylor
Martyn Dewar
Matt Knight
Andrew Ying
Doug Paulley
Ganesh Sittampalam
Alex Skene

- What's on the horizon
This is unmistakably @markcridge's voice - should there be some indication that he's signing off? Like a handwritten 'Mark' signature perhaps? 

- What are you looking forward to in 2021?
Think this needs an indication that they are staff voices - maybe add under the title "Here's what mySociety staff hope the new year will bring."

**Comment by mySocietyClive** [comment]
> Here are some suggested 'Life in lockdown' edits:
> 
> Original
> 
> > Nothing was more challenging than having the kids home for four months while trying to balance our jobs and other commitments. Luckily mySociety is the best possible place to work at times like this. I was given real flexibility and empowered to make the situation work for myself and my family.
> 
> Edit to:
> Having the kids home while trying to balance our jobs and other commitments. Luckily mySociety gave me real flexibility, empowering us to make the situation work for the family.
> 
> Original
> 
> > I worked with a toddler in tow — who doesn’t love having their laptop lid closed mid conference call?
> 
> Edit to keep 'mid' and 'conference' on the same line, separated by a hyphen:
> I worked with a toddler in tow — who doesn’t love having their laptop lid closed mid-conference call?
> 
> Original
> 
> > Migrating all of our digital transformation work with international parliaments to remote-only activity has been really difficult. It is so much harder to build rapport with people, get a sense of how people use technology, and how the digital and physical space in parliaments overlaps, when you are only able to speak to people via Skype. It is made even more difficult when you need simultaneous translation to communicate.
> 
> Edit to:
> 
> Complex digital transformation work with international parliaments is really difficult when you can only speak via Skype. And all the more difficult when you need simultaneous translation to communicate!
> 
> Original
> 
> > I pretty much work entirely from home now, rather than going out on the road for meetings as I’m used to – my last in-person meeting was on 11 March!
> 
> Edit to:
> No more going out on the road for meetings like I used to – my last in-person meeting was on 11 March!
> 
> Original
> 
> > My usual role of organising and managing in-person conferences and events has massively changed this year due to COVID. I do really miss seeing people and the buzz I get from organising in-person convenings 😞
> 
> Edit to:
> My role of organising in-person events has massively changed this year. I do really miss seeing people and the buzz I get from organising in-person convenings 😞
> 
> Original
> 
> > Yeah. I was sceptical that we would get the same kind of participation and collaboration as we do in person. But actually, I’ve found we get more – maybe the introverts are able to contribute more this way.
> 
> Edit to:
> I was sceptical that we would get the same kind of participation as we do in person. But actually, I’ve found we get more – maybe the introverts are able to contribute more this way.
> 
> Original
> 
> > Moved into my youngest child’s old bedroom/nursery – great having my own office. The monkeys on the wall are an added benefit 🐒
> 
> Edit to:
> Moved into my youngest child’s old bedroom – great having my own office. The monkeys on the wall are an added benefit 🐒
> 
> Original
> 
> > It has made me appreciate how flexible, principled, and supportive mySociety is as an organisation to work for. It really feels like we’re all here for each other, and it’s been a joy seeing these people every day, even through the toughest of times.
> 
> Edit to:
> 
> > It has made me appreciate how flexible, principled, and supportive mySociety is as an organisation to work for. It really feels like we’re all here for each other, even through the toughest of times.
> 
> Original
> 
> > What did our team get up to, way from their computers?
> 
> Noticed a typo. Edit to:
> What did we all get up to, _away_ from our computers?
> 
> Also please add these two, before the final 'I got engaged!':
> 
> * I helped design and deliver two curriculums for a coding bootcamp, funded by the West Midlands Authority.
> * My team won a hackathon at Newspeak House focused on helping MPs, and supported them with their Coronavirus Tech Handbook initiative.

**Comment by mySocietyClive** [comment]
@MyfanwyNixon for 'Community' is there a second item we could add for 'What we did in 2020'?

**Comment by struan** [comment]
"I’m looking forward to working with more partners and more parliaments next year, and conducting more research on how to do digital democracy effectively" is repeated in the final "what are you looking forward to in 2021" section

**Comment by MyfanwyNixon** [comment]
>Keeping an eye on our rights.
This is repeated in the transparency section - it is a title and then it is in the text. Remove the second one, thanks!

**Comment by abimysoc** [comment]
Some of the quotes aren't curly e.g. 'society' in Mark's intro.

Mark claims TICTeC was in early March, TICTeC was 24-25 March :)

"Catherine brings us a her" - delete "a"

For me, the 'Jump to section' nav overlaps the text in places:
Screenshot from 2020-12-16 10-03-32

Where we "worked with SpendNetwork on a project around beneficial ownership in public procurement" it looks a bit weird that "procurement" isn't part of the link

but don't report and drive!. - double punctuation

when people make reports and what that tells us - missing punctuation

maybe the introverts are able to contribute more this way - missing punctuation

**Comment by ashapond** [comment]
In the section 'So long and thanks for all the UKCOD', the name 'UK Citizens' Online Democracy' should NOT have an apostrophe.

In Transparency, next to 'Better Understanding' - the question 'who actually uses WhatDoTheyKnow?' can end with the '?' and doesn't need the full stop.

In the tagline to 'Community': '...we worked hard to empower people within their own neighbourhoods' should have a full stop.

**Comment by MyfanwyNixon** [comment]
Additionally to Asha's point, 

>And, in a piece of inhouse research, we asked, who actually uses WhatDoTheyKnow?.

The link is going to the wrong place - should be https://www.mysociety.org/2020/02/24/whatdotheyknow-survey/

**Comment by MyfanwyNixon** [comment]
>our email alerts become all the more important.

We could take the opportunity to link to them: https://www.theyworkforyou.com/alert/

**Comment by MyfanwyNixon** [comment]
Accidental repetition of a quote:

>I was sceptical that we would get the same kind of participation as we do in person. But actually, I’ve found we get more – maybe the introverts are able to contribute more this way.

and

>Having to run interactive workshops entirely remotely was a new thing, and I was sceptical that we would get the same kind of participation and collaboration as we do in person. But actually, I've found we get more - maybe the introverts are able to contribute more this way

I think the easiest thing is just to remove the second one-  it's in a "life in lockdown" section.

**Comment by MyfanwyNixon** [comment]
Footer

>mySociety is a not-for-profit social enterprise, based in the UK but working with partners internationally. We build and share digital technologies that help people be active citizens, across the three areas of Democracy, Transparency, and Community.

Should Climate be added in there?

**Comment by mySocietyClive** [comment]
> Footer
> 
> > mySociety is a not-for-profit social enterprise, based in the UK but working with partners internationally. We build and share digital technologies that help people be active citizens, across the three areas of Democracy, Transparency, and Community.
> 
> Should Climate be added in there?

Could do, I've noticed it's not on the main website footer either.

**Pull request closed without merging**
